### PR TITLE
get_parents function for getting parents by node keys

### PR DESCRIPTION
**Pull request by gnucifer**
Hi again! I'm attempting to implementing breadcrumbs on the site I'm working on, and found it necessary to implement some kind of way of getting all parents of a node. Since I'm a little bit inexperienced I'm not sure if there are better ways of solving this issue, but this is my attempt at providing at least the basics. Sorry for not providing any tests, I might try to add some later.

### CODE REVIEW

**Comment by gnucifer** [comment]
I was a little bit scared of writing tests, but seems pretty easy so I'm writing them now. A little bit unsure of the correct order of returning parents. For breadcrumbs it's nice if the order is root first, but perhaps not conceptually correct really.

**Comment by gnucifer** [comment]
Also added a basic test.

**Comment by pmartinezalvarez** [comment]
Hi! Thanks so much :) I will merge your commits.

But please check the usage of categories to generate the breadcrumbs. It is how it is done on the glayu times theme [page.eex](https://github.com/pmartinezalvarez/glayu-times-theme/blob/master/_layouts/page.eex)

```
<ul class="categories">
  <%= for category <- @page.categories do %>
      <li><a href="<%= category.path %>" class="category"><span><%= category.name %></span></a></li>
   <% end %>
</ul>
```

**Comment by gnucifer** [comment]
Hi! Yes this works for posts I think, but I was attempting to create breadcrumbs for category pages. I now realize that I would have been able to just fetch the first post and get the breadcrumbs from there, also on category pages, so thank you for clearing that up for me. :) But nice of you to merge it anyway.

**Pull request merged**
